name: Comment for PR

on:
  workflow_dispatch:

jobs:
  push-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make changes
        run: |
          git config --global user.email "panjasouptik968.com"
          git config --global user.name "Souptik Panja"

          echo "New changes" >> changes.txt
          git add changes.txt
          git commit -m "Add changes"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          curl -x POST -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"body":"Thank You For Contributiom"}'
          https://api.github.com/repos/Colt-Canada/wvvbw/issues/$PR_NUMBER/comments
          
